name: Helmfile Diff

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Azure login
        id: login
        uses: azure/login@v1.4.3
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Get AKS config
        id: set-context
        uses: azure/aks-set-context@v3
        with:
          resource-group: ${{ secrets.AKS_RESOURCE_GROUP }}
          cluster-name: ${{ secrets.AKS_CLUSTER_NAME }}

      - name: Setup kubectl
        id: install-kubectl
        uses: azure/setup-kubectl@v3

      - name: Get Nodes
        run: kubectl get node

      - name: Helmfile Diff Dev
        uses: helmfile/helmfile-action@v1.0.0
        with:
          helmfile-workdirectory: "./helmfiles/"
          helmfile-version: 'v0.150.0'
          helm-version: 'v3.11.0'
          helm-plugins: >
            https://github.com/databus23/helm-diff,
            https://github.com/jkroepke/helm-secrets
          helmfile-args: diff --environment dev
          helmfile-auto-init: "false"

      - name: Helmfile Diff Stage
        uses: helmfile/helmfile-action@v1.0.0
        with:
          helmfile-workdirectory: "./helmfiles/"
          helmfile-version: 'v0.150.0'
          helm-version: 'v3.11.0'
          helm-plugins: >
            https://github.com/databus23/helm-diff,
            https://github.com/jkroepke/helm-secrets
          helmfile-args: diff --environment stage
          helmfile-auto-init: "false"
