name: Helmfile Apply

on:
  workflow_run:
    branches:
      - main
    workflows: ["Docker Build and Push"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Azure login
        id: login
        uses: azure/login@v1.4.3
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Get AKS config
        id: set-context
        uses: azure/aks-set-context@v3
        with:
          resource-group: ${{ secrets.AKS_RESOURCE_GROUP }}
          cluster-name: ${{ secrets.AKS_CLUSTER_NAME }}

      - name: Setup kubectl
        id: install-kubectl
        uses: azure/setup-kubectl@v3

      - name: Set short SHA
        id: short_sha
        run: echo ::set-env name=SHORT_SHA::$(echo $GITHUB_SHA | cut -c1-7)

      - name: Helmfile Apply Dev
        uses: helmfile/helmfile-action@v1.9.0
        with:
          helmfile-workdirectory: "helmfiles/"
          helmfile-version: 'v0.150.0'
          helm-version: 'v3.11.0'
          helm-plugins: >
            https://github.com/databus23/helm-diff,
            https://github.com/jkroepke/helm-secrets
          helmfile-args: apply --environment dev --set image.tag=${{ steps.short_sha.outputs.SHORT_SHA }}
          helmfile-auto-init: "false"

      - name: Helmfile Apply Stage
        uses: helmfile/helmfile-action@v1.9.0
        with:
          helmfile-workdirectory: "helmfiles/"
          helmfile-version: 'v0.150.0'
          helm-version: 'v3.11.0'
          helm-plugins: >
            https://github.com/databus23/helm-diff,
            https://github.com/jkroepke/helm-secrets
          helmfile-args: apply --environment stage --set image.tag=${{ steps.short_sha.outputs.SHORT_SHA }}
          helmfile-auto-init: "false"
