name: 'Terraform STG Apply'

on:
  push:
    branches:
      - main

env:
  TERRAFORM_VERSION: 1.9.8

jobs:
  aks:
    name: AKS Terraform Apply
    runs-on: ubuntu-latest
    env:
      WORKING_DIRECTORY: terraform/environments/stg/aks

    steps:
      - name: 'Checkout'
        uses: actions/checkout@master

      - name: 'Use terraform ${{ env.TERRAFORM_VERSION }}'
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}

      - name: 'Terraform init'
        id: init
        run: terraform init -backend-config="access_key=${{ secrets.STORAGE_ACCOUNT_ACCESS_KEY }}"
        working-directory: ${{ env.WORKING_DIRECTORY }}

      - name: 'Terraform apply'
        id: apply
        run: |
          terraform apply \
            -auto-approve \
            -var client_id="${{ secrets.ARM_CLIENT_ID }}" \
            -var client_certificate_password="${{ secrets.ARM_CLIENT_CERTIFICATE_PASSWORD }}" \
            -var client_certificate="${{ secrets.ARM_CLIENT_CERTIFICATE }}" \
            -var tenant_id="${{ secrets.ARM_TENANT_ID }}" \
            -var subscription_id="${{ secrets.ARM_SUBSCRIPTION_ID }}"
        working-directory: ${{ env.WORKING_DIRECTORY }}
