name: 'Terraform STG Destroy'

on: workflow_dispatch

env:
  TERRAFORM_VERSION: 1.9.8

jobs:
  aks:
    name: Destroy STG AKS
    runs-on: ubuntu-latest
    env:
      WORKING_DIRECTORY: terraform/environments/stg/aks

    steps:
      - name: 'Checkout'
        uses: actions/checkout@master

      - name: 'Use terraform ${{ env.TERRAFORM_VERSION }}'
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}

      - name: 'Terraform init'
        id: init
        run: terraform init -backend-config="access_key=${{ secrets.STORAGE_ACCOUNT_ACCESS_KEY }}"
        working-directory: ${{ env.WORKING_DIRECTORY }}

      - name: 'Terraform destroy'
        id: destroy
        run: |
          terraform destroy \
            -auto-approve
        working-directory: ${{ env.WORKING_DIRECTORY }}
